name: CI/PR

on: [push, pull_request]

env:
  DEVELOPER: 1

jobs:
  dockerized:
    strategy:
      fail-fast: false
      matrix:
        vector:
        - jobname: pedantic
          image: fedora
    env:
      jobname: ${{matrix.vector.jobname}}
    runs-on: ubuntu-latest
    container: ${{matrix.vector.image}}
    steps:
    - uses: actions/checkout@v1
    - run: ci/install-docker-dependencies.sh
    - name: Run tmate
      shell: bash
      run: |
        # install tmate
        sudo dnf -yq install tmate openssh &&

        # Generate an SSH key (needed for tmate)
        mkdir -p ~/.ssh &&
        echo -e 'y\n' | ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa &&

        # Start tmate session
        tmate -S /tmp/tmate.sock new-session -d &&
        tmate -S /tmp/tmate.sock wait tmate-ready &&

        # Print SSH invocation every 5 seconds, until tmate session has terminated
        while test -e /tmp/tmate.sock
        do
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          sleep 5
        done
    - run: ci/print-test-failures.sh
      if: failure()
    - name: Upload failed tests' directories
      if: failure() && env.FAILED_TEST_ARTIFACTS != ''
      uses: actions/upload-artifact@v1
      with:
        name: failed-tests-${{matrix.vector.jobname}}
        path: ${{env.FAILED_TEST_ARTIFACTS}}
