name: Update Homebrew Tap
on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - id: version
      name: Compute version number
      run: |
        echo "result=$(echo $GITHUB_REF | sed -e "s/^refs\/tags\/v//")" >>$GITHUB_OUTPUT
    - id: hash
      name: Compute release asset hash
      uses: mjcheetham/asset-hash@v1.1
      with:
        asset: /git-(.*)\.pkg/
        hash: sha256
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update scalar Cask
      uses: mjcheetham/update-homebrew@v1.3
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: microsoft/git
        name: microsoft-git
        type: cask
        version: ${{ steps.version.outputs.result }}
        sha256: ${{ steps.hash.outputs.result }}
        alwaysUsePullRequest: false
